- src/main/resources/json/mediatypes.json
> feat: add application/geo+json

- src/main/java/no/fdk/referencedata/eu/datatheme/ConceptSchema.java
- src/main/java/no/fdk/referencedata/eu/datatheme/DataThemeHarvester.java
- src/main/java/no/fdk/referencedata/eu/vocabulary/EUAuthorityOntology.java
- src/test/java/no/fdk/referencedata/eu/datatheme/DataThemeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/datatheme/DataThemeHarvesterTest.java
- src/test/java/no/fdk/referencedata/eu/datatheme/DataThemeServiceIntegrationTest.java
> feat: add eu theme startUse and conceptSchema

- src/main/java/no/fdk/referencedata/eu/accessright/AccessRightService.java
- src/main/java/no/fdk/referencedata/eu/datatheme/DataThemeService.java
- src/main/java/no/fdk/referencedata/eu/eurovoc/EuroVocHarvester.java
- src/main/java/no/fdk/referencedata/eu/eurovoc/EuroVocService.java
- src/main/java/no/fdk/referencedata/eu/filetype/FileTypeService.java
- src/main/java/no/fdk/referencedata/util/Version.java
- src/main/java/no/fdk/referencedata/util/ZipUtils.java
> fix: handle version comparison

- docker-compose.yml
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatement.java
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatementController.java
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatementImporter.java
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatementService.java
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatements.java
- src/main/java/no/fdk/referencedata/vocabulary/AT.java
- src/main/resources/rdf/provenance.ttl
- src/test/java/no/fdk/referencedata/provenancestatement/ProvenanceControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/provenancestatement/ProvenanceServiceTest.java
- src/test/resources/provenance.rdf
> feat: add provenance statements

- src/main/java/no/fdk/referencedata/openlicences/OpenLicense.java
- src/main/java/no/fdk/referencedata/openlicences/OpenLicenseController.java
- src/main/java/no/fdk/referencedata/openlicences/OpenLicenseImporter.java
- src/main/java/no/fdk/referencedata/openlicences/OpenLicenseService.java
- src/main/java/no/fdk/referencedata/openlicences/OpenLicenses.java
- src/main/resources/rdf/open-licenses.ttl
- src/test/java/no/fdk/referencedata/openlicences/OpenLicenseControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/openlicences/OpenLicenseServiceTest.java
- src/test/resources/open-licenses-skos.rdf
> feat: add open licenses

- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystem.java
- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemController.java
- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemImporter.java
- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemService.java
- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystems.java
- src/main/resources/rdf/languages.ttl
- src/test/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemServiceTest.java
- src/test/resources/languages-skos.rdf
> feat: add linguistic-systems

- src/main/java/no/fdk/referencedata/referencetypes/ReferenceType.java
- src/main/java/no/fdk/referencedata/referencetypes/ReferenceTypeController.java
- src/main/java/no/fdk/referencedata/referencetypes/ReferenceTypeImporter.java
- src/main/java/no/fdk/referencedata/referencetypes/ReferenceTypeService.java
- src/main/java/no/fdk/referencedata/referencetypes/ReferenceTypes.java
- src/main/resources/rdf/reference-types.ttl
- src/test/java/no/fdk/referencedata/referencetypes/ReferenceTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/referencetypes/ReferenceTypesServiceTest.java
- src/test/resources/reference-code-skos.ttl
> feat: add reference-types

- src/main/java/no/fdk/referencedata/apistatus/ApiStatus.java
- src/main/java/no/fdk/referencedata/apistatus/ApiStatusController.java
- src/main/java/no/fdk/referencedata/apistatus/ApiStatusImporter.java
- src/main/java/no/fdk/referencedata/apistatus/ApiStatusService.java
- src/main/java/no/fdk/referencedata/apistatus/ApiStatuses.java
- src/main/resources/rdf/api-status.ttl
- src/test/java/no/fdk/referencedata/apistatus/ApiStatusControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/apistatus/ApiStatusServiceTest.java
- src/test/resources/api-status-skos.ttl
> feat: add api-status

- src/main/java/no/fdk/referencedata/graphql/query/ApiSpecificationQuery.java
- src/main/java/no/fdk/referencedata/graphql/query/ApiStatusQuery.java
- src/main/java/no/fdk/referencedata/graphql/query/LinguisticSystemQuery.java
- src/main/java/no/fdk/referencedata/graphql/query/OpenLicenseQuery.java
- src/main/java/no/fdk/referencedata/graphql/query/ProvenanceQuery.java
- src/main/java/no/fdk/referencedata/graphql/query/ReferenceTypeQuery.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/graphql/ApiSpecificationQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/ApiStatusQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/LinguisticSystemQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/OpenLicenseQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/ProvenanceQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/ReferenceTypeQueryIntegrationTest.java
- src/test/resources/graphql/api-specification-by-code.graphql
- src/test/resources/graphql/api-specifications.graphql
- src/test/resources/graphql/api-status-by-code.graphql
- src/test/resources/graphql/api-statuses.graphql
- src/test/resources/graphql/linguistic-system-by-code.graphql
- src/test/resources/graphql/linguistic-systems.graphql
- src/test/resources/graphql/open-license-by-code.graphql
- src/test/resources/graphql/open-licenses.graphql
- src/test/resources/graphql/provenance-statement-by-code.graphql
- src/test/resources/graphql/provenance-statements.graphql
- src/test/resources/graphql/reference-type-by-code.graphql
- src/test/resources/graphql/reference-types.graphql
> add missing graphql

- src/main/resources/logback.xml
> chore: add stacktrace to error log messages

- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivities.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivity.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityController.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityHarvester.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityRepository.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityService.java
- src/main/java/no/fdk/referencedata/eu/vocabulary/EUMainActivity.java
- src/main/java/no/fdk/referencedata/graphql/query/MainActivityQuery.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/LocalHarvesterConfiguration.java
- src/test/java/no/fdk/referencedata/eu/mainactivity/LocalMainActivityHarvester.java
- src/test/java/no/fdk/referencedata/eu/mainactivity/MainActivityControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/mainactivity/MainActivityHarvesterTest.java
- src/test/java/no/fdk/referencedata/eu/mainactivity/MainActivityServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/MainActivityQueryIntegrationTest.java
- src/test/resources/graphql/main-activities.graphql
- src/test/resources/graphql/main-activity-by-code.graphql
- src/test/resources/main-activity-skos.rdf
resolve https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/114
> feat: EU main-activities

- src/main/java/no/fdk/referencedata/digdir/AbstractDataNorgeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleType.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeController.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeRepository.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeService.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypes.java
- src/main/java/no/fdk/referencedata/digdir/vocabulary/RoleTypeVocabulary.java
- src/main/java/no/fdk/referencedata/graphql/query/RoleTypeQuery.java
- src/main/java/no/fdk/referencedata/security/WebSecurityConfig.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/LocalHarvesterConfiguration.java
- src/test/java/no/fdk/referencedata/digdir/roletype/LocalRoleTypeHarvester.java
- src/test/java/no/fdk/referencedata/digdir/roletype/RoleTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/roletype/RoleTypeHarvesterTest.java
- src/test/java/no/fdk/referencedata/digdir/roletype/RoleTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/RoleTypeQueryIntegrationTest.java
- src/test/resources/graphql/role-type-by-code.graphql
- src/test/resources/graphql/role-types.graphql
- src/test/resources/role-type.ttl
> feat: role-types

- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelType.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeController.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeRepository.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeService.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypes.java
- src/main/java/no/fdk/referencedata/digdir/vocabulary/ServiceChannelTypeVocabulary.java
- src/main/java/no/fdk/referencedata/graphql/query/ServiceChannelTypeQuery.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/LocalHarvesterConfiguration.java
- src/test/java/no/fdk/referencedata/digdir/servicechanneltype/LocalServiceChannelTypeHarvester.java
- src/test/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeHarvesterTest.java
- src/test/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/ServiceChannelTypeQueryIntegrationTest.java
- src/test/resources/graphql/service-channel-type-by-code.graphql
- src/test/resources/graphql/service-channel-types.graphql
- src/test/resources/service-channel-type.ttl
> feat: service-channel-types

- src/main/java/no/fdk/referencedata/Scheduler.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceType.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeController.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeRepository.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeService.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypes.java
- src/main/java/no/fdk/referencedata/digdir/vocabulary/EvidenceTypeVocabulary.java
- src/main/java/no/fdk/referencedata/graphql/query/EvidenceTypeQuery.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/LocalHarvesterConfiguration.java
- src/test/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeHarvesterTest.java
- src/test/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/evidencetype/LocalEvidenceTypeHarvester.java
- src/test/java/no/fdk/referencedata/graphql/EvidenceTypeQueryIntegrationTest.java
- src/test/resources/evidence-type.ttl
- src/test/resources/graphql/evidence-type-by-code.graphql
- src/test/resources/graphql/evidence-types.graphql
> feat: evidence-types

- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherType.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypeController.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypeImporter.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypeService.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypes.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatus.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatusController.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatusImporter.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatusService.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatuses.java
- src/main/java/no/fdk/referencedata/graphql/query/ADMSStatusQuery.java
- src/main/java/no/fdk/referencedata/graphql/query/PublisherTypeQuery.java
- src/main/resources/graphql/schema.graphqls
- src/main/resources/rdf/adms-publisher-type.ttl
- src/main/resources/rdf/adms-status.ttl
- src/test/java/no/fdk/referencedata/adms/PublisherTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/adms/PublisherTypeServiceTest.java
- src/test/java/no/fdk/referencedata/adms/StatusControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/adms/StatusServiceTest.java
- src/test/java/no/fdk/referencedata/graphql/ADMSStatusQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/PublisherTypeQueryIntegrationTest.java
- src/test/resources/graphql/adms-status-by-code.graphql
- src/test/resources/graphql/adms-statuses.graphql
- src/test/resources/graphql/publisher-type-by-code.graphql
- src/test/resources/graphql/publisher-types.graphql
> feat: adms status & publisher-types

- src/main/java/no/fdk/referencedata/eu/datatheme/DataThemeController.java
- src/main/java/no/fdk/referencedata/eu/datatheme/DataThemeService.java
- src/test/java/no/fdk/referencedata/eu/datatheme/DataThemeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/datatheme/DataThemeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/DataThemeQueryIntegrationTest.java
> feat: data-themes RDF endpoint

- src/main/java/no/fdk/referencedata/eu/eurovoc/EuroVoc.java
- src/main/java/no/fdk/referencedata/eu/eurovoc/EuroVocHarvester.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/eu/eurovoc/EuroVocServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/EuroVocQueryIntegrationTest.java
- src/test/resources/eurovoc-sparql-result.ttl
- src/test/resources/graphql/eurovoc-by-code.graphql
- src/test/resources/graphql/eurovocs.graphql
> feat: include broader & narrower for eurovocs

- src/main/java/no/fdk/referencedata/Scheduler.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatus.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusController.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusHarvester.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusRepository.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusService.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatuses.java
- src/main/java/no/fdk/referencedata/eu/vocabulary/EUConceptStatus.java
- src/main/java/no/fdk/referencedata/graphql/query/ConceptStatusQuery.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/LocalHarvesterConfiguration.java
- src/test/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusHarvesterTest.java
- src/test/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/conceptstatus/LocalConceptStatusHarvester.java
- src/test/java/no/fdk/referencedata/graphql/ConceptStatusQueryIntegrationTest.java
- src/test/resources/concept-status.ttl
- src/test/resources/graphql/concept-status-by-code.graphql
- src/test/resources/graphql/concept-statuses.graphql
> feat: eu concept-status

- pom.xml
- src/main/java/no/fdk/referencedata/ApplicationSettings.java
- src/main/java/no/fdk/referencedata/Scheduler.java
- src/main/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubject.java
- src/main/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectController.java
- src/main/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectHarvester.java
- src/main/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectRepository.java
- src/main/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectService.java
- src/main/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjects.java
- src/main/java/no/fdk/referencedata/graphql/query/ConceptSubjectQuery.java
- src/main/java/no/fdk/referencedata/security/WebSecurityConfig.java
- src/main/resources/application.yml
- src/main/resources/graphql/schema.graphqls
- src/test/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectHarvesterTest.java
- src/test/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/conceptsubjects/LocalConceptSubjectHarvester.java
- src/test/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusHarvesterTest.java
- src/test/java/no/fdk/referencedata/graphql/ConceptSubjectQueryIntegrationTest.java
- src/test/resources/concept-subjects.ttl
- src/test/resources/graphql/concept-subjects.graphql
resolve #160
Høster samtlige fagområde-kodelister og kan ikke garantere unike koder på tvers av listene, så dropper getByCode
ref endringene i WebSecurityConfig: https://github.com/jzheaux/cve-2023-34035-mitigations
> concept subjects

- pom.xml
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherType.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypeController.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypeRepository.java
- src/main/java/no/fdk/referencedata/adms/publishertype/PublisherTypeService.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatus.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatusController.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatusRepository.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatusService.java
- src/test/java/no/fdk/referencedata/adms/PublisherTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/adms/PublisherTypeServiceTest.java
- src/test/java/no/fdk/referencedata/adms/StatusControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/adms/StatusServiceTest.java
part of https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/165
> adms RDF-endpoints

- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/fylke/FylkeController.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/fylke/FylkeService.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/kommune/KommuneController.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/kommune/KommuneService.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/nasjon/NasjonController.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/nasjon/NasjonService.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/fylke/FylkeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/fylke/FylkeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/kommune/KommuneControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/kommune/KommuneServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/nasjon/NasjonControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/FylkeQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/KommuneQueryIntegrationTest.java
- src/test/resources/fylker.ttl
- src/test/resources/kommuner.ttl
- src/test/resources/nasjoner.ttl
> feat: rdf-endpoints for geonorge administrative enheter

- src/main/java/no/fdk/referencedata/iana/mediatype/MediaTypeController.java
- src/main/java/no/fdk/referencedata/iana/mediatype/MediaTypeService.java
- src/test/java/no/fdk/referencedata/graphql/MediaTypeQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/iana/mediatype/MediaTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/iana/mediatype/MediaTypeServiceIntegrationTest.java
- src/test/resources/media-types.ttl
> feat: rdf-endpoint for iana media types

- src/main/java/no/fdk/referencedata/eu/accessright/AccessRightController.java
- src/main/java/no/fdk/referencedata/eu/accessright/AccessRightService.java
- src/main/java/no/fdk/referencedata/eu/distributiontype/DistributionTypeController.java
- src/main/java/no/fdk/referencedata/eu/distributiontype/DistributionTypeService.java
- src/main/java/no/fdk/referencedata/eu/filetype/FileTypeController.java
- src/main/java/no/fdk/referencedata/eu/filetype/FileTypeService.java
- src/main/java/no/fdk/referencedata/eu/frequency/FrequencyController.java
- src/main/java/no/fdk/referencedata/eu/frequency/FrequencyService.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityController.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityService.java
- src/test/java/no/fdk/referencedata/eu/accessright/AccessRightControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/accessright/AccessRightServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/distributiontype/DistributionTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/distributiontype/DistributionTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/filetype/FileTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/filetype/FileTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/frequency/FrequencyControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/frequency/FrequencyServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/mainactivity/MainActivityControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/mainactivity/MainActivityServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/AccessRightQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/DistributionTypeQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/FileTypeQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/FrequencyQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/MainActivityQueryIntegrationTest.java
> feat: rdf-endpoints for all eu code lists

- src/main/java/no/fdk/referencedata/apispecification/ApiSpecificationController.java
- src/main/java/no/fdk/referencedata/apispecification/ApiSpecificationService.java
- src/main/java/no/fdk/referencedata/apistatus/ApiStatusController.java
- src/main/java/no/fdk/referencedata/apistatus/ApiStatusService.java
- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemController.java
- src/main/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemService.java
- src/main/java/no/fdk/referencedata/openlicences/OpenLicenseController.java
- src/main/java/no/fdk/referencedata/openlicences/OpenLicenseService.java
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatementController.java
- src/main/java/no/fdk/referencedata/provenancestatement/ProvenanceStatementService.java
- src/main/java/no/fdk/referencedata/referencetypes/ReferenceTypeController.java
- src/main/java/no/fdk/referencedata/referencetypes/ReferenceTypeService.java
- src/main/java/no/fdk/referencedata/schema/dayofweek/DayOfWeekController.java
- src/main/java/no/fdk/referencedata/schema/dayofweek/DayOfWeekService.java
- src/test/java/no/fdk/referencedata/apispecification/ApiSpecificationControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/apispecification/ApiSpecificationServiceTest.java
- src/test/java/no/fdk/referencedata/apistatus/ApiStatusControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/apistatus/ApiStatusServiceTest.java
- src/test/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/linguisticsystem/LinguisticSystemServiceTest.java
- src/test/java/no/fdk/referencedata/openlicences/OpenLicenseControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/openlicences/OpenLicenseServiceTest.java
- src/test/java/no/fdk/referencedata/provenancestatement/ProvenanceControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/provenancestatement/ProvenanceServiceTest.java
- src/test/java/no/fdk/referencedata/referencetypes/ReferenceTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/referencetypes/ReferenceTypesServiceTest.java
- src/test/java/no/fdk/referencedata/schema/DayOfWeekControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/schema/DayOfWeekServiceTest.java
> feat: rdf-endpoints

- src/main/java/no/fdk/referencedata/digdir/AbstractDataNorgeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeController.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeService.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeController.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/roletype/RoleTypeService.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeController.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeHarvester.java
- src/main/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeService.java
- src/test/java/no/fdk/referencedata/digdir/conceptsubjects/ConceptSubjectControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/evidencetype/EvidenceTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/roletype/RoleTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/roletype/RoleTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/digdir/servicechanneltype/ServiceChannelTypeServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/EvidenceTypeQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/RoleTypeQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/ServiceChannelTypeQueryIntegrationTest.java
resolves https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/165
> feat: rdf-endpoints for all digdir code lists

- src/main/java/no/fdk/referencedata/eu/AbstractEuHarvester.java
- src/main/java/no/fdk/referencedata/eu/accessright/AccessRightHarvester.java
- src/main/java/no/fdk/referencedata/eu/conceptstatus/ConceptStatusHarvester.java
- src/main/java/no/fdk/referencedata/eu/datasettype/DatasetTypeHarvester.java
- src/main/java/no/fdk/referencedata/eu/distributiontype/DistributionTypeHarvester.java
- src/main/java/no/fdk/referencedata/eu/frequency/FrequencyHarvester.java
- src/main/java/no/fdk/referencedata/eu/mainactivity/MainActivityHarvester.java
- src/test/java/no/fdk/referencedata/eu/datasettype/DatasetTypeControllerIntegrationTest.java
- src/test/resources/dataset-types-translated.ttl
> feat: translate dataset-types on harvest

- .github/workflows/deploy-staging.yaml
- src/main/java/no/fdk/referencedata/Scheduler.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/Enhet.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetController.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetHarvester.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetRepository.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetService.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/Enheter.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/fylke/Fylke.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/kommune/KommuneService.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/nasjon/Nasjon.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/nasjon/NasjonService.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetHarvesterTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/LocalEnhetHarvester.java
- src/test/java/no/fdk/referencedata/graphql/FindByURIsQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/SearchQueryIntegrationTest.java
- src/test/resources/administrative-enheter-harvest.ttl
- src/test/resources/administrative-enheter-result.ttl
> feat: add unified version of administrative enheter

- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetService.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetVariant.java
- src/main/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetVariantRepository.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/geonorge/administrativeenheter/EnhetServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/FindByURIsQueryIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/SearchQueryIntegrationTest.java
- src/test/resources/administrative-enheter-result.ttl
> support variants of administrative enheter

- .github/workflows/deploy-prod&demo.yaml
- .github/workflows/deploy-staging.yaml
- Dockerfile
- README.md
- deploy/base/kustomization.yaml
- deploy/base/reference-data-deployment.yaml
- deploy/base/reference-data-service.yaml
- deploy/demo/env.yaml
- deploy/demo/kustomization.yaml
- deploy/prod/env.yaml
- deploy/prod/kustomization.yaml
- deploy/staging/env.yaml
- deploy/staging/kustomization.yaml
- pom.xml
- src/main/java/no/fdk/referencedata/security/WebSecurityConfig.java
- src/main/resources/application.yml
resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1029
resolve https://github.com/Informasjonsforvaltning/fdk-team-private/issues/105
resolve #245
> CORS & kustomize deploy

- src/main/java/no/fdk/referencedata/Scheduler.java
- src/main/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilities.java
- src/main/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailability.java
- src/main/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityController.java
- src/main/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityHarvester.java
- src/main/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityRepository.java
- src/main/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityService.java
- src/main/java/no/fdk/referencedata/eu/vocabulary/EUPlannedAvailability.java
- src/main/java/no/fdk/referencedata/graphql/query/PlannedAvailabilityQuery.java
- src/main/java/no/fdk/referencedata/settings/Settings.java
- src/main/resources/graphql/schema.graphqls
- src/main/resources/openapi/openapi.yaml
- src/test/java/no/fdk/referencedata/eu/plannedavailability/LocalPlannedAvailabilityHarvester.java
- src/test/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityHarvesterTest.java
- src/test/java/no/fdk/referencedata/eu/plannedavailability/PlannedAvailabilityServiceIntegrationTest.java
- src/test/java/no/fdk/referencedata/graphql/PlannedAvailabilityQueryIntegrationTest.java
- src/test/resources/graphql-test/planned-availabilities.graphql
- src/test/resources/graphql-test/planned-availability-by-code.graphql
- src/test/resources/planned-availability-sparql-result.ttl
> feat: add planned availability from EU

- .gitignore
- deploy/demo/env.yaml
- deploy/prod/env.yaml
- deploy/staging/env.yaml
- src/main/java/no/fdk/referencedata/Scheduler.java
- src/main/java/no/fdk/referencedata/adms/status/ADMSStatus.java
- src/main/java/no/fdk/referencedata/rdf/RDFSource.java
- src/main/resources/application.yml
resolve #251 
resolve #261 
resolve #262
> chore: switch mongodb host

- pom.xml
- src/main/java/no/fdk/referencedata/eu/frequency/FrequencyHarvester.java
- src/test/java/no/fdk/referencedata/eu/frequency/FrequencyControllerIntegrationTest.java
- src/test/java/no/fdk/referencedata/eu/frequency/LocalFrequencyHarvester.java
- src/test/java/no/fdk/referencedata/graphql/FrequencyQueryIntegrationTest.java
- src/test/resources/frequencies-sparql-result.ttl
> feat: add translations for EU frequencies
